spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show-sql: true


logging.level.org.hibernate.type: TRACE



